# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-11 20:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_pass_answer', models.CharField(max_length=255)),
                ('relation_answer', models.CharField(max_length=255)),
                ('personal_answer', models.CharField(max_length=255)),
                ('pay_method_answer', models.CharField(max_length=255)),
                ('age_answer', models.IntegerField(max_length=255)),
            ],
        ),
    ]
